version: "3"

services:
  speedtest:
    build: .
    image: adolfintel/speedtest:${TAG:-latest}
    ports:
      - "8888:80"
    # Should only be declared if you have a custom configuration. 404 errors thrown if misconfigured
    #volumes:
      #- .:/var/www/html
