name: "Bitfocus Companion"
description: "Bitfocus Companion Addon for Home Assistant"
version: "3.3.1"
slug: "bitfocus_companion"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: !secret web_port
options:
  web_port: 8000
