name: Download and Copy Companion Repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download_and_copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Download Companion repository
      run: |
        git clone --depth=1 https://github.com/bitfocus/companion.git companion-temp
        mkdir -p companion
        cp -r companion-temp/* companion/
        rm -rf companion-temp

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add companion/
        git commit -m "Add contents from bitfocus/companion"
        git push
